/*  egModule.c - The simplest kernel module.
 */
#include <linux/kernel.h>
#include <linux/init.h>
#include <linux/module.h>
#include <linux/slab.h>
#include <linux/io.h>
#include <linux/interrupt.h>

#include <linux/of_address.h>
#include <linux/of_device.h>
#include <linux/of_platform.h>

#include <linux/cdev.h>
#include <linux/device.h>
#include <linux/fs.h>
#include <linux/types.h>
#include <linux/uaccess.h>
#include <linux/delay.h>

#include <asm/siginfo.h>
#include <linux/pid_namespace.h>
#include <linux/pid.h>

/* Standard module information, edit as appropriate */
MODULE_LICENSE("GPL");
MODULE_AUTHOR
    ("Xilinx Inc.");
MODULE_DESCRIPTION
    ("egModule - loadable module template generated by petalinux-create -t modules");

#define DRIVER_NAME "egModule"
#define RF_MAX_DEVS 1

/* Simple example of how to receive command line parameters to your module.
   Delete if you don't need them */
unsigned myint = 0xdeadbeef;
char *mystr = "default";

module_param(myint, int, S_IRUGO);
module_param(mystr, charp, S_IRUGO);

struct egModule_local {
	int irq;
	unsigned long mem_start;
	unsigned long mem_end;
	void __iomem *base_addr;
};

typedef struct{
	struct cdev cdev;
	dev_t dev;
	struct class *cl
} plip_private_t;

plip_private_t *intrDemo_priv;

static int pidOwner = 0;
static struct task_struct *current_task;

static void send_signal(int signum) {

	struct pid *current_task_pid;

	if (pidOwner == 0) {
		printk("User process is undefined\n");
		return;
	}

	printk("%s,%d.sending to owner %d\n",__func__, __LINE__, pidOwner);
	struct siginfo info;
	memset(&info, 0, sizeof(struct siginfo));

	info.si_signo = signum;
	info.si_code = 0;
	info.si_int = 1234;

	if (current_task == NULL){
		rcu_read_lock();
		current_task_pid = find_vpid(pidOwner);
		if (current_task_pid == NULL) {
			printk("%s.Fail to find_vpid()\n", __func__);
			rcu_read_unlock();
			return;
		}
		current_task = pid_task(current_task_pid, PIDTYPE_PID);
		if (current_task == NULL) {
			printk("%s.Fail to pid_task()\n", __func__);
			rcu_read_unlock();
			return;
		}
		printk("%s.Found task: %d\n", __func__, current_task->pid);
		rcu_read_unlock();
	}
	int ret = send_sig_info(signum, &info, current_task);
	if (ret < 0) {
	       printk("error sending signal\n");
	}
	return;
}

static irqreturn_t egModule_irq(int irq, void *lp)
{
	printk("egModule interrupt\n");
	send_signal(SIGUSR1);
	return IRQ_HANDLED;
}

static int egModule_probe(struct platform_device *pdev)
{
	struct resource *r_irq; /* Interrupt resources */
	struct resource *r_mem; /* IO mem resources */
	struct device *dev = &pdev->dev;
	struct egModule_local *lp = NULL;

	int rc = 0;
	
	dev_info(dev, "Device Tree Probing\n");

	/* Get iospace for the device */
	r_mem = platform_get_resource(pdev, IORESOURCE_MEM, 0);
	if (!r_mem) {
		dev_err(dev, "invalid address\n");
		return -ENODEV;
	}
	
	lp = (struct egModule_local *) kmalloc(sizeof(struct egModule_local), GFP_KERNEL);
	if (!lp) {
		dev_err(dev, "Cound not allocate egModule device\n");
		return -ENOMEM;
	}
	
	dev_set_drvdata(dev, lp);
	
	lp->mem_start = r_mem->start;
	lp->mem_end = r_mem->end;

	if (!request_mem_region(lp->mem_start,
				lp->mem_end - lp->mem_start + 1,
				DRIVER_NAME)) {
		dev_err(dev, "Couldn't lock memory region at %p\n",
			(void *)lp->mem_start);
		rc = -EBUSY;
		goto error1;
	}

	lp->base_addr = ioremap(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	if (!lp->base_addr) {
		dev_err(dev, "egModule: Could not allocate iomem\n");
		rc = -EIO;
		goto error2;
	}

	/* Get IRQ for the device */
	r_irq = platform_get_resource(pdev, IORESOURCE_IRQ, 0);
	if (!r_irq) {
		dev_info(dev, "no IRQ found\n");
		dev_info(dev, "egModule at 0x%08x mapped to 0x%08x\n",
			(unsigned int __force)lp->mem_start,
			(unsigned int __force)lp->base_addr);
		return 0;
	}
	lp->irq = r_irq->start;
	
	rc = request_irq(lp->irq, &egModule_irq, 0, DRIVER_NAME, lp);
	if (rc) {
		dev_err(dev, "testmodule: Could not allocate interrupt %d.\n",
			lp->irq);
		goto error3;
	}

	dev_info(dev,"egModule at 0x%08x mapped to 0x%08x, irq=%d\n",
		(unsigned int __force)lp->mem_start,
		(unsigned int __force)lp->base_addr,
		lp->irq);
	return 0;
error3:
	free_irq(lp->irq, lp);
error2:
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
error1:
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return rc;
}

static int egModule_remove(struct platform_device *pdev)
{
	struct device *dev = &pdev->dev;
	struct egModule_local *lp = dev_get_drvdata(dev);
	free_irq(lp->irq, lp);
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return 0;
}

#ifdef CONFIG_OF
static struct of_device_id egModule_of_match[] = {
	{ .compatible = "xlnx,counter-intr-1.0", },
	{ /* end of list */ },
};
MODULE_DEVICE_TABLE(of, egModule_of_match);
#else
# define egModule_of_match
#endif


static struct platform_driver egModule_driver = {
	.driver = {
		.name = DRIVER_NAME,
		.owner = THIS_MODULE,
		.of_match_table	= egModule_of_match,
	},
	.probe		= egModule_probe,
	.remove		= egModule_remove,
};

int intrDemo_ioctl(struct file *filep, unsigned int cmd, unsigned long arg){
	if (copy_from_user(&pidOwner, (int *) arg, sizeof(int))) {
		printk("Fail to copy_from_user()\n");
		return -EFAULT;
	}
	printk("%s.pidOwner: %d\n", __func__, pidOwner);
	current_task = NULL;
	return 1;
}

const static struct file_operations rru_fops = {
	// .open = intrDemo_open,
	// .release = intrDemo_release,
	.unlocked_ioctl = intrDemo_ioctl,
};


static int __init egModule_init(void)
{
	printk("<1>Hello module world.\n");
	printk("<1>Module parameters were (0x%08x) and \"%s\"\n", myint,
	       mystr);

	int ret;

	intrDemo_priv = kzalloc(sizeof(plip_private_t), GFP_KERNEL);

	if (!intrDemo_priv)
	{
		return -ENOMEM;
	}

	ret = alloc_chrdev_region(&intrDemo_priv->dev, 0, RF_MAX_DEVS, "intrDemo");

	if (ret < 0) {
		printk("Fail to alloc_chrdev_region()\n");
		return ret;
	}

	if ((intrDemo_priv->cl = class_create(THIS_MODULE, "intrDemo")) == NULL)
	{
		unregister_chrdev_region(intrDemo_priv->dev, 1);
		printk("Fail to class_create()\n");
		return -1;
	}

	if (device_create(intrDemo_priv->cl, NULL, intrDemo_priv->dev, NULL, "intrDemo") == NULL) 
	{
		class_destroy(intrDemo_priv->cl);
		unregister_chrdev_region(intrDemo_priv->dev, 1);
		printk("Fail to device_create()\n");
		return -1;
	}

	cdev_init(&intrDemo_priv->cdev, &rru_fops);
	cdev_add(&intrDemo_priv->cdev, intrDemo_priv->dev, RF_MAX_DEVS);

	// plip_init();

	return platform_driver_register(&egModule_driver);
	return 0;
}


static void __exit egModule_exit(void)
{
	platform_driver_unregister(&egModule_driver);
	printk(KERN_ALERT "Goodbye module world.\n");
}

module_init(egModule_init);
module_exit(egModule_exit);

